### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by akatreyt** [devxoul/UITextView-Placeholder#16]
I'm using this in a custom cell and would like to have the placeholder text have a x padding of 16. Any ways to get this done?

Thanks

**Comment by devxoul** [comment]
Currently there's no way to set only placeholder label's inset, because placeholder label is intended to follow textview's own text properties. You can set `textContainerInset` property of UITextView.

Alternatively, you can use `textView.attributedPlaceholer` to set NSAttributedString with attribute:

```swift
let paragraph = NSMutableParagraphStyle()
paragraph.firstLineHeadIndent = 20

let textView = UITextView()
textView.attributedText = NSAttributedString(
    string: "Hello, World!",
    attributes: [NSParagraphStyleAttributeName: paragraph]
)
```

![screen shot 2015-10-21 at 3 46 12 pm](https://cloud.githubusercontent.com/assets/931655/10629575/e21cd954-780a-11e5-9abf-d5ded1085aab.png)
